### ISSUE TITLE
Code already includes yaml support, doesn't need providing

### ISSUE THREAD

**Issue by devoncarew** [DanTup/Dart-Code#1]
https://github.com/DanTup/Dart-Code/blob/master/syntaxes/yaml.plist

It seems better to just rely on it being available from vscode...

**Comment by DanTup** [comment]
I did think about this, but it doesn't seem to be built-in and it seemed weird to expect people to get another extension. This one is set only to apply to `pubspec.yaml` (and the extension only activates on `.dart` or `pubspec.yaml` so it won't be loaded outside of Dart projects). I figured if someone had a better extension it w/could override it (though I haven't actually seen how to set priorities).

It seems a bit weird to install a Dart extension and not get colors in pubspec?

**Comment by devoncarew** [comment]
I see yaml files syntax highlighted in my copy of vscode, and do see a yaml syntax here: https://github.com/Microsoft/vscode/tree/master/extensions/yaml. You might want to double check your copy of vscode and see if it includes yaml support? Perhaps from the `change language mode` command.

**Comment by DanTup** [comment]
Ok, maybe I added Pubspec to my packages json before testing it and that changed the language from Yaml to Pubspec. I'll investigate and fix later. Thanks!

**Comment by DanTup** [comment]
This is fixed now. I think when I first added it I wanted to activate my extension when opening pubspec.yaml so I declared a language; but subsequently discovered `workspaceContains`.

Gone now, and you'll see `YAML` as the langauge instead of `Pubspec` :-)
