### ISSUE TITLE
Cannot locate Dart SDK

### ISSUE THREAD

**Issue by mit-mit** [DanTup/Dart-Code#21]
This looks exiting! I tried to install on a Mac, but I get the error that it cannot locate the Dart SDK (`Dart-Code: Could not find a Dart SDK to use. Please add it to your PATH or set it in the extensions settings and reload`).

I tried to configure it like this, but I still get the error:

```
$ cat "$HOME/Library/Application Support/Code/User/settings.json"
// Place your settings in this file to overwrite the default settings
{
    "dart.sdkPath": "/usr/local/Cellar/dart/1.18.1/"
}
$
```

**Comment by DanTup** [comment]
Finding automatically on Linux/Mac is a bit broken (#17), but the path should work. Can you confirm whether you have a file at this location?

    /usr/local/Cellar/dart/1.18.1/bin/snapshots/analysis_server.dart.snapshot

**Comment by mit-mit** [comment]
I got it to work! The directory layout homebrew gives you is a bit odd -- the correct path is:

`/usr/local/Cellar/dart/1.18.1/libexec/"`

not

`/usr/local/Cellar/dart/1.18.1/`

**Comment by DanTup** [comment]
Gotcha!

I'd like to detect the location if I can (to avoid forcing the user to manually provide it); could you confirm whether the "dart" that's in your path is a symlink to `/usr/local/Cellar/dart/1.18.1/libexec/bin/dart` then?

**Comment by mit-mit** [comment]
Yup:

```
$ which dart
/usr/local/bin/dart
$ ll /usr/local/bin/dart
lrwxr-xr-x  1 mit  admin  30 Aug  5 12:38 /usr/local/bin/dart -> ../Cellar/dart/1.18.1/bin/dart
$ ll /usr/local/Cellar/dart/1.18.1/bin/dart
lrwxr-xr-x  1 mit  admin  19 Aug  5 12:38 /usr/local/Cellar/dart/1.18.1/bin/dart -> ../libexec/bin/dart
$
```

**Comment by DanTup** [comment]
Thanks for the help. In that case I think this is just a dupe of #17 which is fixed in latest code (it correctly handles paths on Linux/Mac and follows symlinks).

I hope to push a preview version to the marketplace this weekend with these fixes.

**Comment by DanTup** [comment]
If you remove the old version you can install a new preview from the VS Code marketplace which resolves the SDK issues (you can remove the `sdkPath` and it should still work):

https://marketplace.visualstudio.com/items?itemName=DanTup.dart-code

**Comment by mit-mit** [comment]
Thanks, that works great!

**Comment by DanTup** [comment]
Excellent; thanks for confirming! :)
