### ISSUE TITLE
Rename from "Dart-Code" to "Dart Code"

### ISSUE THREAD

**Issue by devoncarew** [DanTup/Dart-Code#23]
I don't see a lot of hyphens in the names of VSCode extensions. `Dart` would be ideal, but I guess already taken. Perhaps coordinate w/ the other plugin author? Or change the name to `DartCode`, `Dart Code`, `Dart Tooling`, ... ?

**Comment by DanTup** [comment]
I did actually write it as "Dart Code" originally; can't remember why I changed. But it has been bugging me lately too, so maybe I'll go back.

Not sure if the other plugin is active (last commit was April), but might give the author a shout.
