### ISSUE TITLE
Add a DefinitionProvider to support Go-To Definition

### ISSUE THREAD

**Issue by devoncarew** [DanTup/Dart-Code#28]
To support jump to definition.

**Comment by DanTup** [comment]
Whoops, should've already had a case about this! IIRC the data for this is sent via notifications (`analysis.navigation`) so I'll need to keep hold of all of that data somewhere for when it's needed?

**Comment by DanTup** [comment]
https://code.visualstudio.com/docs/extensionAPI/vscode-api#DefinitionProvider

**Comment by DanTup** [comment]
Actually, seems like there's an `analysis.getNavigation` too, so maybe I don't need to keep this all from the notifications at all.

**Comment by DanTup** [comment]
This is done, but I can't make it work for SDK files so I've raised #35 to add that once I figured it out (the problem seems to be [no startLine/startColumn for SDK files](https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/VGmyyvsfdI8)).

**Comment by devoncarew** [comment]
> IIRC the data for this is sent via notifications (analysis.navigation) so I'll need to keep hold of all of that data somewhere for when it's needed?

Navigation can come in as events, or as an explicit call, but looks like you found `analysisGetNavigation` already :)

**Comment by devoncarew** [comment]
Re: that bug, that's probably due to some summary work - the SDK analysis is summarized and stored on disk, instead of being analyzed for each project.

**Comment by DanTup** [comment]
Ok, I've just filtered them out for now and I'll deal with it in #35 if/when there's a good solution.
