### ISSUE TITLE
Add language configuration file for brace/quote completion (etc.)

### ISSUE THREAD

**Issue by devoncarew** [DanTup/Dart-Code#3]
Similar to this one: https://github.com/Microsoft/vscode/blob/master/extensions/typescript/language-configuration.json (and referenced by the package.json file).

**Comment by DanTup** [comment]
Do you know if there's documentation on this? It's the first I've seen of one and I can't find much info about it. I can obviously set the values in that one, but it there are more options it'd be good to know the full schema!

**Comment by devoncarew** [comment]
I don't know of any docs unfortunately, but I did find a whole bunch of examples in the languages impls here: https://github.com/Microsoft/vscode/tree/master/extensions.

**Comment by DanTup** [comment]
This stuff doesn't work for me, but in [this PR](https://github.com/PowerShell/vscode-powershell/pull/229) it suggests that this has changed in the July release. The current stable version is the June release.

I'll wait until the next update before doing anything with this (trying to keep on the stable branch for now).

**Comment by devoncarew** [comment]
Ah, cool.

**Comment by DanTup** [comment]
The [July update](https://code.visualstudio.com/updates/July_2016#_extension-authoring) is out. The release notes don't suggest this is new (only changes to it) so I'm confused why this didn't seem to work. In any case, I'll give it another crack soon :-)

**Comment by DanTup** [comment]
Actually, the `autoClosingPairs` thing sounds new, and that was actually the thing I was using to test the file; so the other stuff maybe would've worked (if I knew exactly what each of the other settings was doing!).

**Comment by devoncarew** [comment]
I think it's things like:
- selecting a char matching the one your cursor is on
- auto-closing things like braces
- if you have some text selected, and type one of the specified chars (`'`, `(`, `{`, ...), the editor will surround the text with those chars instead of replacing the text

**Comment by DanTup** [comment]
The things that I wasn't sure about where:

- What does it do with `comments` (other than disabling `autoClosingPairs`, but maybe that's all)
- What's the difference between things in `brackets` and `surroundingPairs`?

I'll put a file in and have a play around and see what I can figure out. I suspect starting with the TS one and tweaking will probably give reasonable behaviour.

**Comment by devoncarew** [comment]
Comments I suspect controls things like `cmd-/` (line comment and uncomment). But I also don't have any real sense of exactly what things do. Perhaps a bug against VSCode to provide some docs?

**Comment by DanTup** [comment]
Think I figured most out:

- `comments.lineComment` is used as you say for commenting out
- `blockComment` unsure ??
- `brackets` will automatically cause indents if you press enter between a pair (surroundingPairs don't)
- `autoClosingPairs` obviously provides closing character automatically and can be excluded from strings and comments (not sure if there are any other options allowed here?)
- `surroundingPars` highlights the other part of the pair (but without adding the indent functionality that `brackets` get)

I raised https://github.com/Microsoft/vscode/issues/10198 (I suspect MS are sick of me this week ;)) asking about docs.

I couldn't actually find anything to change about the typescript one; it all seemed correct (to me, a Dart noob). Can you see anything missing/wrong?

**Comment by devoncarew** [comment]
> I couldn't actually find anything to change about the typescript one; it all seemed correct (to me, a Dart noob). Can you see anything missing/wrong?

No, not really :) backticks only really mean something to dart in dartdoc comments, but it can't hurt to have them act like single or double quotes elsewhere - it'd be useful to the user and consistent w/ the other types of quotes.

**Comment by DanTup** [comment]
heh, I got confused that thought they were used for string interpolation but I guess my TS/Dart is blurring somewhat having two Code windows open, writing one in each!

Thanks!
