### ISSUE TITLE
Check if we need to subscribe to analysis.flushResults

### ISSUE THREAD

**Issue by DanTup** [DanTup/Dart-Code#33]
Looks like [this](https://htmlpreview.github.io/?https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/doc/api.html#notification_analysis.flushResults) would be sent if a file was deleted. Need to check if Code already removes listed errors for deleted files (if not, we should subscribe this and then set an empty set of errors for that file path).

**Comment by ikhwanhayat** [comment]
From my observation:

1) If the file is currently active in the editor, when deleted, it's error list is cleared.

2) If the file is not opened, or opened but not active, when deleted, it's error list is NOT cleared.

If guess the safest is to listen to `analysis.flushResults` notification and remove the errors manually.

I'm currently working on this one.

**Comment by DanTup** [comment]
Good stuff; thanks! :-)
