### ISSUE TITLE
Review outline ranges in document symbol provider

### ISSUE THREAD

**Issue by DanTup** [DanTup/Dart-Code#52]
(Splitting this out of #45 because that's merged and getting long...)

@devoncarew

I noticed that with the current document outlines, the highlights aren't the same as TypeScript (which highlights a whole class/method/whatever):

![TS outline](https://cloud.githubusercontent.com/assets/1078012/17527847/e6a6ba8a-5e64-11e6-91e2-100ab749ce7b.png)

If I change the code to use the offset/length from the outline instead of the element it's much closer, but seems to include whitespace before it (so the closing `}` of a method is highlighted for the next method; I think this is by design based on earlier discussions with BW on the analyzer list).

I think I could make it work the same by using the start position from `element` but the end from `outline` (Code seems to always highlight full lines), however it feels a little bit wonky.

What do you think?

**Comment by devoncarew** [comment]
I think its OK that the highlights are a little different; probably what's important is that the user gets a sense of where the element is in the file and can scan the contents.

**Comment by DanTup** [comment]
But without the full range, it can't/won't try to fit the whole body on
screen as you go through them?

>

**Comment by devoncarew** [comment]
Personally, that's not a huge concern to me, but I can see the value of working similarly to other vscode plugins.

**Comment by DanTup** [comment]
I'll have a look at tweaking this tonight. Although the code might be a bit weird if we take the start from one and end from another, I think the result is nicer (and I'm happy to write more/weird code for that, as long as it's stable).

Thanks again!

**Comment by DanTup** [comment]
These tweaks seem to work great; the highlighted block now matches what you'd expect (and is the same as TypeScript extension). If you spot anything wonky with it, let me know!

**Comment by devoncarew** [comment]
Tried it out - looks great!
